### ISSUE TITLE
Review `SmiTag`

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#10]
The current implementation shifts the value by 32-bits for a 64-bit architecture, which is based off of the MIPS implementation that does the same. This seems wrong. The ARM backend shifts the value by 1, as I would expect. Investigate this further.

**Comment by fw-brice** [comment]
I tested the change to make this function just shift the value left by 1, which seems to be the correct behavior, but this did not affect any test cases. This requires more investigation into why it does what it does now, and how that change does not affect anything. Is it perhaps not being used?

**Comment by luyahan** [comment]
It may  depends on `V8_COMPRESS_POINTERS`
```
#ifdef V8_COMPRESS_POINTERS
static_assert(
    kApiSystemPointerSize == kApiInt64Size,
    "Pointer compression can be enabled only for 64-bit architectures");
const int kApiTaggedSize = kApiInt32Size;
#else
const int kApiTaggedSize = kApiSystemPointerSize;
#endif

#ifdef V8_31BIT_SMIS_ON_64BIT_ARCH
using PlatformSmiTagging = SmiTagging<kApiInt32Size>;
#else
using PlatformSmiTagging = SmiTagging<kApiTaggedSize>;
#endif
```
```
// TODO(ishell): Consinder adding kSmiShiftBits = kSmiShiftSize + kSmiTagSize
// since it's used much more often than the inividual constants.
const int kSmiShiftSize = PlatformSmiTagging::kSmiShiftSize;
```
```
template <>
struct SmiTagging<4> {
  enum { kSmiShiftSize = 0, kSmiValueSize = 31 };

template <>
struct SmiTagging<8> {
  enum { kSmiShiftSize = 31, kSmiValueSize = 32 };
````

```

**Comment by fw-brice** [comment]
Yahan's comment above is correct. This can be closed.
