### ISSUE TITLE
Triage and prioritize cctest failures in native build

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#106]
Currently `cctest` pass-rate is less than 70% (see [test status](https://github.com/v8-riscv/v8/wiki/Testing-Status#cross-compiled-v8-riscv-testing)). Need to get a bigger picture of where `cctest` are failing.

[ ] Please post an up-to-date cctest run log somewhere as it shows which tests are failing and the failure messages.
[ ] Sort out cctest failures, identify issues that 1) cause the most test failures; or 2) failures that manifest in smaller test cases; or 3) failures that trigger internal assert errors (those may be easier to debug), and open issues for those failures first

**Comment by penguinwu** [comment]
@lazyparser I'd like to get a better understanding of where we are on the native/qemu runs. Current testing status tracks only the success-rate, but does not provide detailed information of which tests (especially `cctest`) are failing and whether issues have been created to the common or critical failures.

Once the cctest run log is posted, I can work w/ the assignee to triage and prioritize the issues.  Doing this step smartly (i.e., exposing bugs in smaller and simpler tests) can save a lot of debugging time.

**Comment by lazyparser** [comment]
@luyahan and I would run & triage the bugs in HiFive Unleashed.

@thomasyonug @LOGQTAINIA could run QEMU ;-)

**Comment by penguinwu** [comment]
Please remember to share the `run.log` somewhere that others can see. I'd like to take a look at the raw logs.

**Comment by luyahan** [comment]
[log-error.txt](https://github.com/v8-riscv/v8/files/5025678/log-error.txt)
This is a log ran last week.

**Comment by luyahan** [comment]
I have updated test status.
[log-cctest.txt](https://github.com/v8-riscv/v8/files/5026259/log-cctest.txt)
[log-unittests.txt](https://github.com/v8-riscv/v8/files/5026260/log-unittests.txt)

**Comment by luyahan** [comment]
uinttests:
```
[----------] Global test environment tear-down
[==========] 3294 tests from 323 test suites ran. (570833 ms total)
[  PASSED  ] 3293 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SpacesTest.OffThreadSpaceMergeDuringIncrementalMarking
```

**Comment by luyahan** [comment]
intl:
```
yahan@fedora-riscv-sifive:~ $ python2 ./tools/run-tests.py --outdir=./riscv64.native.release/  intl | tee log-intl.txt
Build found: /home/yahan/./riscv64.native.release
>>> Running tests for riscv64.debug
>>> Running with test processors
=== intl/regress-9812 ===                   ^Bd
Warning: unknown flag --enable-slow-asserts.
Try --help for options
366
/home/yahan/test/intl/assert.js:105: Error: Failure (Using Intl.DateFormat formatRange with en-001-u-ca-islamic should not throw): expected <no expection>, found <exception: TypeError: Internal error. Icu error.>.
  throw new Error(message);
  ^
Error: Failure (Using Intl.DateFormat formatRange with en-001-u-ca-islamic should not throw): expected <no expection>, found <exception: TypeError: Internal error. Icu error.>.
    at fail (/home/yahan/test/intl/assert.js:105:9)
    at assertDoesNotThrow (/home/yahan/test/intl/assert.js:182:5)
    at /home/yahan/test/intl/regress-9812.js:61:5
    at Array.forEach (<anonymous>)
    at /home/yahan/test/intl/regress-9812.js:59:11
    at Array.forEach (<anonymous>)
    at /home/yahan/test/intl/regress-9812.js:58:11
Command: riscv64.native.release/d8 --test test/intl/assert.js test/intl/utils.js test/intl/regress-9812.js --random-seed=2057794159 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
[02:11|%  96|+ 217|-   1]: Done
>>> 225 base tests produced 218 (96%) non-filtered tests
>>> 218 tests ran
```

**Comment by luyahan** [comment]
ICU c++代码报错, U_MISSING_RESOURCE_ERROR

**Comment by lazyparser** [comment]
I've tested the latest commit (9b902c290c364e4bb25315f440a0d7f2086ff2c4) on QEMU 5.0.0 with fedora developer 20200108

the result is surprisingly better than two weeks before.

(tips: you might need to enlarge the raw disk image up to 50GB : https://fedoraproject.org/wiki/Architectures/RISC-V/Installing#Optional:_expand_the_disk_image )

(the wiki will be updated after the last three test sets finished)

```
Command: riscv64.native.debug/cctest test-cpu-profiler/DeoptAtSecondLevelInlinedSource --random-seed=1960583998 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner
[60:01|%  99|+ 6522|-   2]: Done
>>> 6579 base tests produced 6524 (99%) non-filtered tests
>>> 6524 tests ran
[root@fedora-riscv ~]#

[root@fedora-riscv ~]# python2 ./tools/run-tests.py --outdir=riscv64.native.debug/ unittests | tee unittests.log
Build found: /root/riscv64.native.debug
>>> Running tests for riscv64.debug
>>> Running with test processors
[20:18|%  99|+ 3282|-   0]: Done
>>> 3295 base tests produced 3282 (99%) non-filtered tests
>>> 3282 tests ran
[root@fedora-riscv ~]#

Command: riscv64.native.debug/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/wasm/regress-1010272.js --random-seed=2044730249 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --wasm-grow-shared-memory --experimental-wasm-threads
[54:29|%  96|+ 4881|-   3]: Done
>>> 5062 base tests produced 4884 (96%) non-filtered tests
>>> 4884 tests ran

[root@fedora-riscv ~]# python2 ./tools/run-tests.py --outdir=riscv64.native.debug/ intl | tee intl.log
Build found: /root/riscv64.native.debug
>>> Running tests for riscv64.debug
>>> Running with test processors
[01:58|%  96|+ 218|-   0]: Done
>>> 225 base tests produced 218 (96%) non-filtered tests
>>> 218 tests ran

[root@fedora-riscv ~]# python2 ./tools/run-tests.py --outdir=riscv64.native.debug/ intl | tee intl.log
Build found: /root/riscv64.native.debug
>>> Running tests for riscv64.debug
>>> Running with test processors
[01:58|%  96|+ 218|-   0]: Done
>>> 225 base tests produced 218 (96%) non-filtered tests
>>> 218 tests ran

[root@fedora-riscv ~]# python2 ./tools/run-tests.py --outdir=riscv64.native.debug/ message
Build found: /root/riscv64.native.debug
>>> Running tests for riscv64.debug
>>> Running with test processors
[01:59|%  48|+ 296|-   0]: Done
>>> 609 base tests produced 296 (48%) non-filtered tests
>>> 296 tests ran

[root@fedora-riscv ~]# python2 ./tools/run-tests.py --outdir=riscv64.native.debug/ inspector
Build found: /root/riscv64.native.debug
>>> Running tests for riscv64.debug
>>> Running with test processors
[04:00|%  48|+ 253|-   0]: Done
>>> 522 base tests produced 253 (48%) non-filtered tests
>>> 253 tests ran

[root@fedora-riscv ~]# python2 ./tools/run-tests.py --outdir=riscv64.native.debug/ debugger
Build found: /root/riscv64.native.debug
>>> Running tests for riscv64.debug
>>> Running with test processors
[04:04|%  97|+ 308|-   0]: Done
>>> 316 base tests produced 308 (97%) non-filtered tests
>>> 308 tests ran
[root@fedora-riscv ~]#
```

**Comment by penguinwu** [comment]
@luyahan Could you add HiFive board details to the testing status page https://github.com/v8-riscv/v8/wiki/Testing-Status#running-on-hifive-unleashed-board?

**Comment by luyahan** [comment]
> @luyahan Could you add HiFive board details to the testing status page https://github.com/v8-riscv/v8/wiki/Testing-Status#running-on-hifive-unleashed-board?

Is your mean  add error log into wiki? I add it later.

**Comment by lazyparser** [comment]
> > @luyahan Could you add HiFive board details to the testing status page https://github.com/v8-riscv/v8/wiki/Testing-Status#running-on-hifive-unleashed-board?
> 
> Is your mean add error log into wiki? I will add it later.

- [ ] the hardware details of the board: https://www.sifive.com/boards/hifive-unleashed
- [ ] the OS details of the board: Fedora Developer Rawhide [VERSION @luyahan ]

**Comment by penguinwu** [comment]
I mean the hardware and OS details (not the error logs).

**Comment by luyahan** [comment]
> I mean the hardware and OS details (not the error logs).

I had added it on wiki.

**Comment by penguinwu** [comment]
@luyahan Can this one be closed?

**Comment by luyahan** [comment]
everything is ok.
