### ISSUE TITLE
Decide base NodeJS version and setup NodeJS repo 

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#107]
Decide the basic NodeJS version that we would like to bring up and the corresponding V8 version/tag. Setup NodeJS repo under v8-riscv/ and the wiki on how to build NodJS (using v8-riscv) in QEMU/real hardware.

Dependency: rebasing v8 to the chosen version #19.

**Comment by penguinwu** [comment]
@fw-brice Can this one be closed?

**Comment by fw-brice** [comment]
The repo has indeed been setup - https://github.com/v8-riscv/node
Based on Yahan's work, I started with v14.0.0.

The setup is still in progress as there is no wiki yet and Yahan's changes have not been merged in yet.

**Comment by luyahan** [comment]
the version of v8 in latest nodejs repo is 8.4.x.x . our v8 version is 8.6.0.0 @fw-brice
