### ISSUE TITLE
Investigate the feasibility and benefit of 32-bit build

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#109]
**Feasibility investigation**

[ ] Is it possible to cross-compile a 32-bit V8 for RISCV? If not, is it caused by dependence on 32-bit supports of other components? 
[ ] Is it possible to run a 32-bit RISCV application on a 64-bit Linux distribution?

** Benefit investigation**
[ ] Are there significant memory footprint savings of running 32-bit V8 vs 64-bit V8? This can be estimated on ARM (32- vs. 64-bit V8). Or use other mechanisms to estimate the saving

**Comment by chaoRIOS** [comment]
[x] Is it possible to run a 32-bit RISCV application on a 64-bit Linux distribution?

It seems not work in this way

**Comment by penguinwu** [comment]
Close long-term issues to keep current issue list for more immediate items
