### ISSUE TITLE
Rewrite `RV_li`

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#11]
Originally, code in `RV_li` was copied from LLVM. Rewrite this code from scratch so that we can remove the LLVM license.

**Comment by fw-brice** [comment]
This is referring to the method, `Assembler::RV_li(Register rd, int64_t imm)`, in _assembler-riscv64.cc_. It should be able to take any 64-bit integer and load it into the register using an optimal sequence of instructions.

The method `Assembler::li_constant(Register rd, int64_t imm)` may need to be updated as well. This version should emit a consistent number of instructions, regardless of what the immediate is (so not optimized).

**Comment by penguinwu** [comment]
@fw-brice can we close this one?
