### ISSUE TITLE
Investigate on enabling V8 on hardware without floating-point extensions

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#110]
The current backend supports the complete functionality of V8 using `RV64I` and `M`, `A`, `F`, `D`, `Zicsr`, `Zifence` extensions. Is this the minimal ISA requirement? In particular, can V8 be built without floating-point ISA support (e.g., using softfloat)?

**Comment by penguinwu** [comment]
long-term issue, closed for now to keep issue list clean

**Comment by lazyparser** [comment]
Let's move it (as long term project) to the wishlist 2021 :) issue #366
