### ISSUE TITLE
Functional testing of v8 benchmarks

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#116]
Follow the instructions [here](https://v8.dev/docs/benchmarks) to functionally test V8 benchmarks (those are different from `run_tests.py` test suite). We do not care about performance at this point, so do not report any performance number, just the pass rate and open issues for failures.

Need to test the following configurations:
- simulated.debug build
- simulated.release build
- simulated.debug build w/ stress-opt 
- QEMU debug build
- HiGive debug build

Please add pass-rate results to https://github.com/v8-riscv/v8/wiki/Testing-Status.

**Comment by lazyparser** [comment]
FYI
v8-riscv seems passed sunspider and kraken benchmark. no error reported by csuite.py.

hit an crash https://github.com/v8-riscv/v8/issues/129 when run octane benchark.

**Comment by lazyparser** [comment]
current:

- [x]     simulated.debug build
- [ ]     simulated.release build
- [ ]     simulated.debug build w/ stress-opt
- [x]     QEMU debug build
- [x]     HiGive debug build

**Comment by penguinwu** [comment]
@lazyparser Could you test the simulated build and stress-opt options so that we can close this issue?

**Comment by lazyparser** [comment]
no problem. I missed stress-opt options. will test it today or night.

**Comment by penguinwu** [comment]
All build options are tested. Close this one.
