### ISSUE TITLE
Improve management of `t5` and `t6`

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#117]
There is a nice mechanism to manage the use of asembler scratch register `t3`, via `UseScratchRegisterScope`. We also use `t5` and `t6` as assembler scratch registers, but their use is very ad-hoc, other than ensuring that the trampoline pool generation does not happen while they are live. All three registers should be able to use the same technique to manage their scope.

**Comment by LOGQTAINIA** [comment]
Hi, brice. 

May I ask you a question? I wonder that what the exact meaning of this sentence.

> other than ensuring that the trampoline pool generation does not happen while they are live. 

I checked the code in `src/codegen/riscv64/macro-assembler-riscv64.cc`. And I found that the most of usage of t5 and t6 are following with `src/codegen/riscv64/macro-assembler-riscv64.cc`.

For an instance.

```
void MacroAssembler::AssertBoundFunction(Register object) {
  if (emit_debug_code()) {
    BlockTrampolinePoolScope block_trampoline_pool(this);
    STATIC_ASSERT(kSmiTag == 0);
    SmiTst(object, t5);
    Check(ne, AbortReason::kOperandIsASmiAndNotABoundFunction, t5,
          Operand(zero_reg));
    GetObjectType(object, t5, t5);
    Check(eq, AbortReason::kOperandIsNotABoundFunction, t5,
          Operand(JS_BOUND_FUNCTION_TYPE));
  }
}
```

Does that mean `their use is very ad-hoc`? 

If I use these code to replace all use of t5 and t6, is it safe and no side effect?

```
UseScratchRegisterScope temps(this);
Register scratch = temps.Acquire();
```

**Comment by fw-brice** [comment]
Yes, their use is very ad-hoc, except that you should always see the following when they are used:

```
BlockTrampolinePoolScope block_trampoline_pool(this);
```

That is because `t5` and `t6` are used when creating the trampoline pool, so the above scope ensures that the trampoline pool is not generated while t5 or t6 are live elsewhere. You will need to take into account this requirement for the trampoline pool when you solve this problem.

I just looked, and it seems that the trampoline creation now only uses t5, not t6.

**Comment by penguinwu** [comment]
@fw-brice Can this be closed?

**Comment by fw-brice** [comment]
Yes! Thanks to @LOGQTAINIA.
