### ISSUE TITLE
Address RISC-V FIXMEs in the source code

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#119]
Need to go through all the  `FIXME (RISCV)` in the source code and resolve them or open issues if need further investigation.

**Comment by penguinwu** [comment]
@fw-brice did we go through all the FIXMEs from RISCV as part of the upstreaming process? Do you feel that we can close this one?

**Comment by lazyparser** [comment]
If there are still some FIXME exist, we can triage them and find out easy todos as good-first-bug for new interns. I am optimistic that 5~10 new contributors will join during the 2021H1

**Comment by fw-brice** [comment]
That sounds good Wei. I will review the existing spots and see if any require a new issue to be opened.

**Comment by fw-brice** [comment]
Ok, I reviewed the remaining FIXMEs, fixed some of them in #379 and opened issues 370-378 for the remaining.
