### ISSUE TITLE
Identify and triage remaining issues with `riscv64` branch

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#127]
**Describe the bug**
In the `riscv64` branch, I have rebased our RISC-V changes on the tip from upstream. I have resolved all issues with the build, but there are currently 100 tests that fail. These need to be triaged and resolved so that we may make this our main branch.

**To Reproduce**
1. Start with a clean directory and get the v8 source as described [here](https://github.com/v8-riscv/v8/wiki/get-the-source#checkout-v8-source-from-google) but do not checkout `8.1.268`, just leave the tip, and do not checkout an older version of `third_party/icu` as described there.
2. Add our repo as described [here](https://github.com/v8-riscv/v8/wiki/get-the-source#checkout-the-risc-v-branch)
3. Checkout branch `riscv64`
4. Build as usual, following steps [here](https://github.com/v8-riscv/v8/wiki/simulator-build)
5. Run `v8-riscv-tools/test-riscv.sh`

**Expected behavior**
```
[05:08|%  78|+ 13797|- 100]: Done
 >>> 17700 base tests produced 16805 (94%) non-filtered tests
 >>> 13897 tests ran
```

**Comment by penguinwu** [comment]
All failures are triaged and issues opened.
