### ISSUE TITLE
Enable more wasm-spec-tests

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#13]
There is a large discrepency between tests run by the `arm64.simulated` build and r`iscv64.simulated.debug` build that cannot be completely accounted for by known failures in `f32` and `f64` tests.

| build | tests passed | run rate |
| - | - | - | 
| arm64.simulated | 203 | 49% |
| riscv64.simulated.debug | 85 | 44% |  

Need to investigate `wasm-spec-tests.status` to run all the skipped tests for riscv64 and see if we can enable more tests or identify new issues.

Since our backend is closest to mips64 backend, please add mips64 run-rate and test passed stats to the table as well.

**Comment by lazyparser** [comment]
@luyahan are you working on (partially) this area?

**Comment by penguinwu** [comment]
After rebasing the latest V8 and #167, we run 177 tests for this suite.

**Comment by penguinwu** [comment]
Look like we are getting very close to ARM run stats, close this one.
