### ISSUE TITLE
[Rebased V8 branch] Internal error: execution/riscv64/frame-constants-riscv64.h, line 87

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#136]
**Describe the bug**
Trigger V8 internal error:
```
# Fatal error in ../../src/execution/riscv64/frame-constants-riscv64.h, line 87
# Debug check failed: 0 != kPushedFpRegs & (1 << reg_code) (0 vs. 0).
```

**To Reproduce**
1. Build simulated debug build for rebased-v8 branch (follow build instruction in #127 
2. Run test/program 'out/riscv64.sim/cctest test-wasm-breakpoints/RunWasmLiftoff_WasmGetLocalsAndStack'
3. See error

```
# Fatal error in ../../src/execution/riscv64/frame-constants-riscv64.h, line 87
# Debug check failed: 0 != kPushedFpRegs & (1 << reg_code) (0 vs. 0).
```
**Expected behavior**
A successful run has no output.

**Additional context**
Another test fails the same way:
```
out/riscv64.sim/cctest test-wasm-breakpoints/RunWasmTurbofan_WasmGetLocalsAndStack
```

**Comment by lazyparser** [comment]
FYI I could not reproduce this issue:

```
wuwei@plct-build-5:~/v8riscv/v8$ cat out/riscv64.sim/args.gn
is_component_build = false
is_debug = true
target_cpu = "x64"
v8_target_cpu = "riscv64"
use_goma = false
goma_dir = "None"
wuwei@plct-build-5:~/v8riscv/v8$ out/riscv64.sim/cctest test-wasm-breakpoints/RunWasmLiftoff_WasmGetLocalsAndStack
Break #0
Break #1
Break #2
Break #3
Break #4
Break #5
Break #6
Break #7
Break #8
Break #9
Break #10
wuwei@plct-build-5:~/v8riscv/v8$ git log -1
commit ac0bf66b416ec164dc583a007fc546afbfe8991d (HEAD -> riscv-porting-dev, riscv/riscv-porting-dev)
Author: Wei Wu <lazyparser@gmail.com>
Date:   Fri Aug 7 09:57:59 2020 +0800

    [CI] Change the output style to verbose

    This patch changes the output style of run-tests.py from the
    default 'mono' style to 'verbose' for more useful CI log.

    The problem of the mono style is that we could not figure out
    easily which testcase failed and what the error message was.
    And redirecting the output of run-tests.py could also capture
    lots of control & invisable ASCII chars, which is not useful.
wuwei@plct-build-5:~/v8riscv/v8$
```

**Comment by lazyparser** [comment]
oh, I see. this is a bug report targeting `riscv64` branch.

so It would be better to have a prefix like `[b/riscv64]` for different branch?

**Comment by penguinwu** [comment]
Right, these issues show up in rebased V8 branch. I forgot to mention that they require a slightly different build process, will update the description and put `[Rebase V8]` on the title.

**Comment by penguinwu** [comment]
The assertion error was caused by the mismatch between `kPushedFpRegs` and `kLiftoffAssemblerFpCacheRegs`. After setting `kPushedFpRegs` according to `kLiftoffAssemblerFpCacheRegs`, the problem is fixed.

Fixed in `riscv64` branch.
