### ISSUE TITLE
Investigate using constant-pool to optimize loading of large immediate values

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#157]
Loading certain 32- or 64-bit immediate values can take up to 6 instructions (see implementation of `TurboAssembler::Li`). In such cases, it may be more beneficial to store the immediate value in a constant pool during code-gen, and then generates a load instruction for load immediate.

Investigate the constant-pool mechanism in other backends to evaluate the feability of implementing it for RISCV backend

**Comment by luyahan** [comment]
I try to Investigate  it.

**Comment by penguinwu** [comment]
@luyahan Can this one be closed? If so, please close it.

**Comment by luyahan** [comment]
#226 had complete it.
