### ISSUE TITLE
Release build compiler error for `src/objects/intl-objects.cc`

### ISSUE THREAD

**Issue by derekztu22** [v8-riscv/v8#169]
**Describe the bug**
Building the release build for the simulator build for riscv64 branch fails compilation

**To Reproduce**
1. Build `riscv64.release` following instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build#build-v8-release-simulated-build)
2. Error is seen as follows
```bash
../../src/objects/intl-objects.cc:50:1: error: static_assert failed due to requirement '67 <= 65' "v8 is required to build with ICU 67 and up"
static_assert(
^
1 error generated.
[1277/1507] CXX obj/v8_base_without_compiler/elements.o
ninja: build stopped: subcommand failed.
Error! - V8 compilation finished with errors.
```

**Expected behavior**
Clean compilation

**Comment by thomasyonug** [comment]
Maybe you can try to checkout master branch of icu under third_party dir

**Comment by lazyparser** [comment]
run `gclient sync` after switched to riscv64 branch

**Comment by derekztu22** [comment]
Running `gclient sync` after switching works
