### ISSUE TITLE
Remove the patch step

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#17]
In our current build instructions, users are required to manually patch some code in the build directory, because it comes from another repository. The correct solution would be to also fork this repository and have users pull our changes from the fork.

**Comment by penguinwu** [comment]
@fw-brice Shall we close this one?

**Comment by fw-brice** [comment]
Yes, I think we can close this. We still require the patch, but let's just let it get resolved once we upstream. We don't need to fork the other upstream repo.
