### ISSUE TITLE
[CI] Include release build in QEMU and HiFive runs (before 2020-09-04)

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#180]
biweekly task

run both {sim,cross} x {debug,release} x {cctests, etc}

**Comment by lazyparser** [comment]
the script is done.

and we found the release build will hang in QEMU when running sunspider.

**Comment by lazyparser** [comment]
the script is temporally stored at 
https://github.com/isrc-cas/PLCT-Toolbox/blob/master/v8team/v8-ci-qemu.sh

would mv/cp to v8-riscv-tools/ later.

**Comment by penguinwu** [comment]
Let's skip sunspider from the script and open an issue on sunspider.
