### ISSUE TITLE
[CI] Enable CI on external cloud instance (need to send the result back to github via REST API) (before 2020-09-04)

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#182]
to speed up CI build & test

**Comment by lazyparser** [comment]
still working on this issue. I failed to find enough time to work through. hopefully would have another try in this week.

**Comment by lazyparser** [comment]
@fw-brice has done using the github actions. (fast CI bot)
I push testing results to slack. (full/slow CI bot)

Done.

**Comment by fw-brice** [comment]
Just to clarify in case someone looks at this later to make changes, the fast CI is triggered by webhooks, then sends the status back via the REST API. It does not use GitHub Actions. You can see the code here - https://github.com/v8-riscv/v8-riscv-ci

**Comment by lazyparser** [comment]
> Just to clarify in case someone looks at this later to make changes, the fast CI is triggered by webhooks, then sends the status back via the REST API. It does not use GitHub Actions. You can see the code here - https://github.com/v8-riscv/v8-riscv-ci

Got it. Glad to see the codes are also open source :-)
