### ISSUE TITLE
Compare dynamic instruction count of running RISCV64 and MIPS64 backend

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#195]
This task is the starting point of conducting performance analysis for the RISCV64 backend. We start by comparing codes generated by MIPS64 and RISCV64 backends.

- [ ] Select which test cases or benchmarks to be included in the study. It is always good to start with some simple examples first, then move onto benchmarks (see [here](https://v8.dev/docs/benchmarks))
- [ ] Augment simulator-riscv64 and simulator-mips64 to printout dynamic instruction count w/o dumping the full trace (because for larger programs, the instruction trace may be too large)
- [ ] Collect dynamic instruction count for RISCV and MIPS64 for each of the selected program and plot the the ratio.

**Comment by lazyparser** [comment]
@penguinwu so are you working on this task now?

**Comment by penguinwu** [comment]
No, I am not working on it. Feel free to assign to someone in your team.

**Comment by luyahan** [comment]
I had add a tools to compare it.

**Comment by penguinwu** [comment]
Excellent! The next step is to run the tool through the benchmarks and collect the stats (e.g., how many more instructions compared to MIPS). @luyahan

**Comment by penguinwu** [comment]
Done
