### ISSUE TITLE
Support `TurboAssembler::LoadLabel(Register dest, Label x)`

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#198]
This code snippet is from `code-generator-riscv64.cc`, we have encountered the assert failure `CHECK_EQ(offset, __ SizeOfCodeGeneratedSince(&start_call));` several times in the development process.  `offset` statically estimates the number of instructions generated between label `start_call` and the sequence of instructions generated by `__CallCfunction`. With changes to code-gen, sometimes we need to update `offset` value (this has happend twice before during the development process). Furthermore, `offset` value may differ among different builds. Therefore the following code is quite brittle.
```
      // from start_call to return address
      int offset = __ root_array_available() ? 64 : 72;
#if V8_HOST_ARCH_RISCV64
      if (__ emit_debug_code()) {
        offset += 16;
      }
#endif
      if (isWasmCapiFunction) {
        // Put the return address in a stack slot.
        __ bind(&start_call);
        __ auipc(kScratchReg, 0);
        __ Add64(kScratchReg, kScratchReg, offset); // <== offset specifies the PC difference between label `start_call` and the instruction after `__CallCfunction` sequence
        __ Sd(kScratchReg,
              MemOperand(fp, WasmExitFrameConstants::kCallingPCOffset));
      }
      if (instr->InputAt(0)->IsImmediate()) {
        ExternalReference ref = i.InputExternalReference(0);
        __ CallCFunction(ref, num_parameters);
      } else {
        Register func = i.InputRegister(0);
        __ CallCFunction(func, num_parameters);
      }
      if (isWasmCapiFunction) {
        **CHECK_EQ(offset, __ SizeOfCodeGeneratedSince(&start_call));** <== Assert failure in different builds as # instr generated differs
        RecordSafepoint(instr->reference_map(), Safepoint::kNoLazyDeopt);
      }
```

A robust way to implement `offset` is to follow the implementation of branch offsets through labels (where branch offsets are resolved after codes are generated and patched to the instruction buffer). I propose we introduce a new `TurboAssembler` API that loads the PC represented by a label into a register (e.g., `LoadLabel(Register dest, Label x)`). The actual value of the label represented by (`auipc + offset`) is calculated when `offset` is resolved through the same mechanism that `label` offset is resolved. So the above code can be implemented as follows:
```
      // from start_call to return address
      int offset = __ root_array_available() ? 64 : 72;
#if V8_HOST_ARCH_RISCV64
      if (__ emit_debug_code()) {
        offset += 16;
      }
#endif
      if (isWasmCapiFunction) {
        // Put the return address in a stack slot.
        __ loadLabel(kScratchReg, after_cccall); <== Changed code
        __ Sd(kScratchReg,
              MemOperand(fp, WasmExitFrameConstants::kCallingPCOffset));
      }
      if (instr->InputAt(0)->IsImmediate()) {
        ExternalReference ref = i.InputExternalReference(0);
        __ CallCFunction(ref, num_parameters);
      } else {
        Register func = i.InputRegister(0);
        __ CallCFunction(func, num_parameters);
      }

     bind(&after_ccall); <== changed code
      if (isWasmCapiFunction) {
        RecordSafepoint(instr->reference_map(), Safepoint::kNoLazyDeopt);
      }
```

This will address the failures in #197 and the wasm-api failures in the board (not sure if there is an issue assigned).

**Comment by penguinwu** [comment]
@fw-brice @luyahan Since you worked on labels and label resolution, what do you think about this solution? Please comment.

**Comment by luyahan** [comment]
I agree this solution.

**Comment by fw-brice** [comment]
I agree. This makes the code cleaner and less brittle.

**Comment by penguinwu** [comment]
@LOGQTAINIA Assign this one to you as it is related to the WIP PR #197.

**Comment by luyahan** [comment]
#202 had merged
