### ISSUE TITLE
Run tests through jitless mode

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#200]
#199 shows that `jitless` mode may expose new bugs. Let's run all our tests and benchmarks using the jitless modes and triage any new issues exposed.

**Comment by lazyparser** [comment]
I tried to add jitless as an argument in `run-tests.py` but it could not recog it. How to add the jitless tests to our CI? Do we have any instructions & scripts for it?

**Comment by penguinwu** [comment]
not needed any more.
