### ISSUE TITLE
riscv64 native release build hangs in QEMU when running sunspider

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#208]
**Describe the bug**
riscv64 native release build hangs in QEMU when running sunspider

**To Reproduce**
1. Build with options: follow the wiki
2. Run test/program: uncomment [L175](https://github.com/isrc-cas/PLCT-Toolbox/blob/master/v8team/v8-ci-qemu.sh#L175) and run the check script. 
3. See error (hang)

**Expected behavior**
same as the debug build. output three line logs.

**Errors/Logs**
it never stops. at least 12 hours.

**Additional context**
I have not dig into it yet. anyone who are interested can claim this issue.

**Comment by penguinwu** [comment]
Does it hang in simulated release build too?

**Comment by fw-brice** [comment]
Please try this again after #245 is merged. There is a good chance this is the same problem.

**Comment by lazyparser** [comment]
Fixed. good job!

**Comment by fw-brice** [comment]
Great. Thanks!
