### ISSUE TITLE
Investigate how to use LLVM to build V8

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#211]
Identify issues that would block building v8-riscv using the LLVM toolchain instead of the GCC toolchain (current). The benefit of using LLVM toolchain is that it is consistent w/ the standard build process of V8.

**Comment by lazyparser** [comment]
log:
try to build llvm on risc-v qemu (fedora) and got a few errors:

http://paste.ubuntu.com/p/pqt22gyxnj/

try cross build later.

**Comment by penguinwu** [comment]
This is a longer term item, close it for now.
