### ISSUE TITLE
[QEMU] === cctest/test-cpu-profiler/DeoptAtSecondLevelInlinedSource === failed

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#216]
**Describe the bug**
```
=== cctest/test-cpu-profiler/DeoptAtSecondLevelInlinedSource ===
--- stderr ---
#
# Fatal error in ../../src/execution/frames.h, line 154
# Debug check failed: static_cast<uintptr_t>(type) < Type::NUMBER_OF_TYPES (137436291256 vs. 23).
#
#
#
#FailureMessage Object: 0x3fffaeb068
==== C stack trace ===============================

    /root/riscv64.native.debug/cctest(+0x3461a68) [0x2ac3071a68]
    /root/riscv64.native.debug/cctest(+0x33b8412) [0x2ac2fc8412]
    /root/riscv64.native.debug/cctest(+0x31a1d82) [0x2ac2db1d82]
    /root/riscv64.native.debug/cctest(+0x31a1dac) [0x2ac2db1dac]
    /root/riscv64.native.debug/cctest(+0x1273666) [0x2ac0e83666]
    /root/riscv64.native.debug/cctest(+0x126e64e) [0x2ac0e7e64e]
    /root/riscv64.native.debug/cctest(+0x126e6ea) [0x2ac0e7e6ea]
    /root/riscv64.native.debug/cctest(+0x126e784) [0x2ac0e7e784]
    /root/riscv64.native.debug/cctest(+0x174a038) [0x2ac135a038]
    /root/riscv64.native.debug/cctest(+0x174a6b8) [0x2ac135a6b8]
    /root/riscv64.native.debug/cctest(+0x171a4ba) [0x2ac132a4ba]
    /root/riscv64.native.debug/cctest(+0x1abf50a) [0x2ac16cf50a]
    /root/riscv64.native.debug/cctest(+0x1abf58e) [0x2ac16cf58e]
    linux-vdso.so.1(__vdso_rt_sigreturn+0) [0x3ff3633800]
    /root/riscv64.native.debug/cctest(+0x12182b0) [0x2ac0e282b0]
    [0x3fe71c34d0]
Command: /root/riscv64.native.debug/cctest test-cpu-profiler/DeoptAtSecondLevelInlinedSource --random-seed=-617479117 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner

```

**To Reproduce**
1. Build with options '...' cross-build
2. Run test/program '...'
3. See error

**Expected behavior**

**Errors/Logs**
If applicable, copy/paste the errors or log messages here.

**Additional context**

**Comment by luyahan** [comment]
It is same wit #237

**Comment by luyahan** [comment]
> **Describe the bug**
> 
> ```
> === cctest/test-cpu-profiler/DeoptAtSecondLevelInlinedSource ===
> --- stderr ---
> #
> # Fatal error in ../../src/execution/frames.h, line 154
> # Debug check failed: static_cast<uintptr_t>(type) < Type::NUMBER_OF_TYPES (137436291256 vs. 23).
> #
> #
> #
> #FailureMessage Object: 0x3fffaeb068
> ==== C stack trace ===============================
> 
>     /root/riscv64.native.debug/cctest(+0x3461a68) [0x2ac3071a68]
>     /root/riscv64.native.debug/cctest(+0x33b8412) [0x2ac2fc8412]
>     /root/riscv64.native.debug/cctest(+0x31a1d82) [0x2ac2db1d82]
>     /root/riscv64.native.debug/cctest(+0x31a1dac) [0x2ac2db1dac]
>     /root/riscv64.native.debug/cctest(+0x1273666) [0x2ac0e83666]
>     /root/riscv64.native.debug/cctest(+0x126e64e) [0x2ac0e7e64e]
>     /root/riscv64.native.debug/cctest(+0x126e6ea) [0x2ac0e7e6ea]
>     /root/riscv64.native.debug/cctest(+0x126e784) [0x2ac0e7e784]
>     /root/riscv64.native.debug/cctest(+0x174a038) [0x2ac135a038]
>     /root/riscv64.native.debug/cctest(+0x174a6b8) [0x2ac135a6b8]
>     /root/riscv64.native.debug/cctest(+0x171a4ba) [0x2ac132a4ba]
>     /root/riscv64.native.debug/cctest(+0x1abf50a) [0x2ac16cf50a]
>     /root/riscv64.native.debug/cctest(+0x1abf58e) [0x2ac16cf58e]
>     linux-vdso.so.1(__vdso_rt_sigreturn+0) [0x3ff3633800]
>     /root/riscv64.native.debug/cctest(+0x12182b0) [0x2ac0e282b0]
>     [0x3fe71c34d0]
> Command: /root/riscv64.native.debug/cctest test-cpu-profiler/DeoptAtSecondLevelInlinedSource --random-seed=-617479117 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner
> ```
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Build with options '...' cross-build
> 2. Run test/program '...'
> 3. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Errors/Logs**
> If applicable, copy/paste the errors or log messages here.
> 
> **Additional context**
> Add any other context about the problem here.
