### ISSUE TITLE
riscv64 native release build hangs in QEMU when running kraken

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#219]
**Describe the bug**
riscv64 native release build hangs in QEMU when running kraken.
while debug build run succeed.

**To Reproduce**
1. Build with options '...' cross build
2. Run test/program '...' run in qemu https://github.com/isrc-cas/PLCT-Toolbox/blob/master/v8team/v8-ci-qemu.sh#L171
3. See error

**Expected behavior**
quit normally.

**Errors/Logs**
run 10+ hours. not quit.

**Additional context**
#208

**Comment by fw-brice** [comment]
Please try this again after #245 is merged. There is a good chance this is the same problem.

**Comment by lazyparser** [comment]
Fixed.
