### ISSUE TITLE
Setup wiki as github repo so that wiki changes can accept pull request

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#24]
Hi,

we can contribute to code repo using PR, but can't do it to wiki.

Is there some way for us to send a pull request to wiki?

**Comment by penguinwu** [comment]
Yes, you have to be a member to edit wiki. We are considering to setup a repo for the wiki so that wiki changes can be reviewed. So I will keep this issue open but update the title to reflect that.

**Comment by fw-brice** [comment]
I will set this up using the technique described here - https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html. This seems like a nice workaround and is easy to implement and maintain.

**Comment by penguinwu** [comment]
Current mechanism of updating the wiki seems to work fine. Right now no need to setup a pull request system for wiki. Close this one.
