### ISSUE TITLE
Hanging test: test/mjsunit/regress/regress-crbug-941743.js

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#246]
**Describe the bug**
This test case hangs on the release build.

**To Reproduce**
1. Build release build (see instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build))
2. Run the test:
```
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-crbug-941743.js --random-seed=1635423114 --nohard-abort --testing-d8-test-runner --allow-natives-syntax --noenable-slow-asserts --nostress-opt --noalways-opt
```
3. This program seems to hang forever

**Expected behavior**
This test should not hang.

**Additional context**
This hang occurs still after the fix for #89 is applied (PR #245).

**Comment by fw-brice** [comment]
I noticed that this test is skipped in _mjsunit.status_ for simulated builds because it is slow:

```
['simulator_run', {
  # Skip/annotate tests that are too slow on simulators.
  ...
  'regress/regress-crbug-941743': [SKIP],
  ...
}],  # simulator_run
```

It is also skipped for `mode == debug` with the comment `# Skip slow tests in debug mode.`.

@lazyparser - Can someone from the lab try this test case on the board and let me know if it hangs there? Thanks.

**Comment by fw-brice** [comment]
I just left it running on the simulator for a while and found that it did indeed finish successfully. I will go ahead and close this.

**Comment by lazyparser** [comment]
copy. will check it and report if it hangs.
