### ISSUE TITLE
Test randomly crash

### ISSUE THREAD

**Issue by DrRezaYazdani1** [v8-riscv/v8#262]
Bug description:
Test behaves differently on different runs. Sometimes aborts, and sometimes produces correct results. I saw this behavior in "debug" build and could not make it to crash in release mode. It looks like an uninitialized variable.

**To Reproduce**
1. Build with options 'debug build'
2. Run test/program. You need to run it many times to see the abort. Many times it passes without error.

out/riscv64.debug/cctest test-cpu-profiler/CrossScriptInliningCallerLineNumbers --random-seed=1527786004 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner

3. See error
#
# Fatal error in ../../src/execution/frames.h, line 154
# Debug check failed: static_cast<uintptr_t>(type) < Type::NUMBER_OF_TYPES (47129821741984 vs. 23).
#
#
#
#FailureMessage Object: 0x7ffeb7063650
==== C stack trace ===============================

    out/riscv64.debug/cctest(v8::base::debug::StackTrace::StackTrace()+0x21) [0x55ba89727dd1]
    out/riscv64.debug/cctest(+0x7a51cba) [0x55ba8971ecba]
    out/riscv64.debug/cctest(V8_Fatal(char const*, int, char const*, ...)+0x26f) [0x55ba89462bcf]
    out/riscv64.debug/cctest(+0x779551c) [0x55ba8946251c]
    out/riscv64.debug/cctest(V8_Dcheck(char const*, int, char const*)+0x27) [0x55ba89462c87]
    out/riscv64.debug/cctest(v8::internal::StackFrame::MarkerToType(long)+0xae) [0x55ba869fed9e]
    out/riscv64.debug/cctest(v8::internal::StackFrame::ComputeType(v8::internal::StackFrameIteratorBase const*, v8::internal::StackFrame::State*)+0x4b8) [0x55ba869f4fe8]
    out/riscv64.debug/cctest(v8::internal::StackFrame::GetCallerState(v8::internal::StackFrame::State*) const+0x36) [0x55ba869f5c56]
    out/riscv64.debug/cctest(v8::internal::SafeStackFrameIterator::IsValidCaller(v8::internal::StackFrame*)+0x19d) [0x55ba869f575d]
    out/riscv64.debug/cctest(v8::internal::SafeStackFrameIterator::AdvanceOneFrame()+0xc2) [0x55ba869f5452]
    out/riscv64.debug/cctest(v8::internal::SafeStackFrameIterator::Advance()+0x1d) [0x55ba869f512d]
    out/riscv64.debug/cctest(v8::internal::TickSample::GetStackSample(v8::internal::Isolate*, v8::RegisterState*, v8::internal::TickSample::RecordCEntryFrame, void**, unsigned long, v8::SampleInfo*, bool, void**)+0x854) [0x55ba871d2e84]
    out/riscv64.debug/cctest(v8::internal::TickSample::Init(v8::internal::Isolate*, v8::RegisterState const&, v8::internal::TickSample::RecordCEntryFrame, bool, bool, v8::base::TimeDelta)+0x134) [0x55ba871d2504]
    out/riscv64.debug/cctest(v8::internal::CpuSampler::SampleStack(v8::RegisterState const&)+0xb6) [0x55ba87158eb6]
    out/riscv64.debug/cctest(v8::sampler::SamplerManager::DoSample(v8::RegisterState const&)+0x203) [0x55ba87704233]
    out/riscv64.debug/cctest(v8::sampler::SignalHandler::HandleProfilerSignal(int, siginfo_t*, void*)+0x8b) [0x55ba8770435b]
    /lib/x86_64-linux-gnu/libpthread.so.0(+0x128a0) [0x7ff8192ca8a0]
    out/riscv64.debug/cctest(v8::internal::RegisterValues::SetRegister(unsigned int, long)+0x8) [0x55ba86984098]
    out/riscv64.debug/cctest(v8::internal::FrameDescription::SetRegister(unsigned int, long)+0x2c) [0x55ba8698458c]
    out/riscv64.debug/cctest(v8::internal::FrameDescription::FrameDescription(unsigned int, int)+0x8d) [0x55ba869780ad]
    out/riscv64.debug/cctest(v8::internal::Deoptimizer::DoComputeInterpretedFrame(v8::internal::TranslatedFrame*, int, bool)+0x3bc) [0x55ba86972ccc]
    out/riscv64.debug/cctest(v8::internal::Deoptimizer::DoComputeOutputFrames()+0x936) [0x55ba86970926]
    out/riscv64.debug/cctest(v8::internal::Deoptimizer::ComputeOutputFrames(v8::internal::Deoptimizer*)+0x15) [0x55ba8696ffe5]
    out/riscv64.debug/cctest(v8::internal::Simulator::SoftwareInterrupt()+0xa0c) [0x55ba8768ad8c]
    out/riscv64.debug/cctest(v8::internal::Simulator::DecodeRVIType()+0xe21) [0x55ba87691e61]
    out/riscv64.debug/cctest(v8::internal::Simulator::InstructionDecode(v8::internal::Instruction*)+0x21c) [0x55ba87687e4c]
    out/riscv64.debug/cctest(v8::internal::Simulator::Execute()+0xb5) [0x55ba87693685]
    out/riscv64.debug/cctest(v8::internal::Simulator::CallInternal(unsigned long)+0x2da) [0x55ba8769398a]
    out/riscv64.debug/cctest(v8::internal::Simulator::CallImpl(unsigned long, int, long const*)+0x39e) [0x55ba8769438e]
    out/riscv64.debug/cctest(unsigned long v8::internal::SimulatorBase::VariadicCall<unsigned long, v8::internal::Simulator, long (v8::internal::Simulator::*)(unsigned long, int, long const*), unsigned long, unsigned long, unsigned long$
    out/riscv64.debug/cctest(unsigned long v8::internal::Simulator::Call<unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**>(unsigned long, unsigned long, unsigned long, unsigned long, unsig$
    out/riscv64.debug/cctest(v8::internal::GeneratedCode<unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned long**>::Call(unsigned long, unsigned long, unsigned long, unsigned long, long, unsigned $
    out/riscv64.debug/cctest(+0x4d23273) [0x55ba869f0273]
    out/riscv64.debug/cctest(v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*)+0x91) [0x55ba86$
    out/riscv64.debug/cctest(v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*)+0x3f5) [0x55ba866c1cf5]
    out/riscv64.debug/cctest(v8::internal::test_cpu_profiler::ProfilerHelper::Run(v8::Local<v8::Function>, v8::Local<v8::Value>*, int, unsigned int, unsigned int, v8::CpuProfilingMode, unsigned int, v8::Local<v8::Context>)+0x1a5) [0x55b$
    out/riscv64.debug/cctest(+0x428be79) [0x55ba85f58e79]
    out/riscv64.debug/cctest(CcTest::Run()+0x21c) [0x55ba859aa41c]
    out/riscv64.debug/cctest(main+0x43d) [0x55ba859ab84d]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7ff81872ab97]
    out/riscv64.debug/cctest(_start+0x2a) [0x55ba859a9fea]
Aborted (core dumped)

**Expected behavior**
reza@olabg13083:~/v8/v8$ !!
out/riscv64.debug/cctest test-cpu-profiler/CrossScriptInliningCallerLineNumbers --random-seed=1527786004 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner
[Top down]:
    0  (root):0 3 0 #1
  123    start:9 0 4 #3 script_b:9
            ;;; deopted at script_id: 4 position: 263 with reason 'Insufficient type feedback for call'.
  500      level1:11 0 3 #4 script_a:13
              ;;; deopted at script_id: 3 position: 192 with reason 'Insufficient type feedback for call'.
   99        action:16 0 3 #7 script_a:8
                 bailed out due to 'Optimization is always disabled'
13884        action:15 0 3 #6 script_a:8
                 bailed out due to 'Optimization is always disabled'
   95        action:14 0 3 #5 script_a:8
                 bailed out due to 'Optimization is always disabled'
    4    (program):0 3 0 #2

It passes some times and aborts some other times.

**Additional context**

**Comment by luyahan** [comment]
relate #237

**Comment by fw-brice** [comment]
I can't reproduce this. @DrRezaYazdani1, please check if you can still reproduce.

**Comment by luyahan** [comment]
can't reproduce it
