### ISSUE TITLE
New failures when using `gm riscv64.debug.check`

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#270]
**Describe the bug**
Using this standard method to build and test the debug configuration causes 100 new failures.

**To Reproduce**
1. Build and test with `gm riscv64.debug.check`
2. See error

**Expected behavior**
0 unexpected failures

**Errors/Logs**
```
73|+ 12562|- 100]: Done
```
This indicates 100 new failures. Most (if not all) of these new errors seem to have the same symptom:

```
 # Fatal error in ../../src/handles/handles.h, line 144
 # Check failed: !v8::internal::FLAG_enable_slow_asserts || (IsDereferenceAllowed()).
```

**Additional context**
When compared to the way we normally build our debug configuration, we can see the following differences in the build arguments:
```diff
1c1
< is_component_build = false
---
> is_component_build = true
2a3
> symbol_level = 2
6a8,10
> v8_enable_backtrace = true
> v8_enable_fast_mksnapshot = true
> v8_enable_slow_dchecks = true
```

**Comment by fw-brice** [comment]
An interesting note is that on our debug build, where these tests pass, we do see a warning, "Warning: unknown flag --enable-slow-asserts." That seems to point to the issue being related to the `v8_enable_slow_dchecks` build argument.

**Comment by luyahan** [comment]
i found it on #224

**Comment by fw-brice** [comment]
Thanks @luyahan, I missed that.

Duplicate of #224.
