### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#290]
**Describe the bug**
This issue shows up when using the `rebase-to-tip` branch (#273). `rebase-to-tip` has been merged, so this occurs on our main branch, `riscv64`.

**To Reproduce**
1. Checkout `rebase-to-tip`
2. Follow standard build procedure
3. Run the test:
```
out/riscv64.sim/cctest test-orderedhashtable/SmallOrderedNameDictionarySetAndMigrateHash --random-seed=-1445372902 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner
```

**Expected behavior**
I expected this test to pass.

**Errors/Logs**
```
Segmentation fault (core dumped)
```

**Possibly related failures:**
* cctest/test-orderedhashtable/SmallOrderedNameDictionaryInsertionMax

**Comment by luyahan** [comment]
it also appear on mips64el.debug

**Comment by fw-brice** [comment]
This works now.
