### ISSUE TITLE
TurboAssembler API refactoring

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#3]
Our turbo assembler APIs still follow the naming convention of the MIPS backend (e.g., `Daddu`). Should refactor to reflect RISCV instruction naming convention.

**Comment by luyahan** [comment]
The API Mul on riscv64 emit mulw, but on mips64 is mul. 
These instr are some differences，so may be cause some error on actual hardware.
And on riscv64,there is no mulh for 32bit mul.API Mulh emit a 64bit mul intrs.

**Comment by penguinwu** [comment]
Went through all the `TurboAssembler` APIs,  about 37 APIs need to be refactored.
- The majority of the APIs to be refactored are integer operations with 64- and 32-bit variations  (e.g., `Daddu` vs `Addu`, or `Dsll` vs `Sll`), those will be refactored into `Add64` vs `Add32`
- Floating-point load/store APIs such as `Ldc1` or `Sdc1` (where c1 refers to FPU in MIPS) will be refactored to `LoadFloat` or `StoreDouble` 
- `Seb` and `Seh` refers to sign-extend byte or half-word, will be refactored to `SignExtendByte` and `SignExtendHalfword`

After this issue is done, need to do a similar refactoring for `kRiscvXXX` names

**Comment by penguinwu** [comment]
Majority of the refactoring is done. The remaining ones will be covered by individual issues, so close this one.
