### ISSUE TITLE
Figure out Spike license

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#300]
There is a TODO in _simulator-riscv.h_: `TODO: Add Spike License here`. This needs to be resolved before upstreaming.

**Comment by fw-brice** [comment]
I'm looking at the code in the simulator, and I'm not seeing much that is directly copied from Spike other than these four definitions directly below the comment and some other trivial code:
```cpp
#define sext32(x) ((sreg_t)(int32_t)(x))
#define zext32(x) ((reg_t)(uint32_t)(x))
#define sext_xlen(x) (((sreg_t)(x) << (64 - xlen)) >> (64 - xlen))
#define zext_xlen(x) (((reg_t)(x) << (64 - xlen)) >> (64 - xlen))
```
I think that we may not need to include anything about the Spike license. @lazyparser, @penguinwu could you please also take a look and let me know what you think?

**Comment by lazyparser** [comment]
Generally, if we have imported codes from the spike-simulator repo before,  it would be better to include the LICENSE in the sub directory if the license was different with the main project. for the TODO I wonder if it was saying `TODO: add copyright string here`? 

The code above looks trivial to me. I am not sure whether we should include the license/copyright string neither. @penguinwu what is your opinion?

**Comment by penguinwu** [comment]
Those codes seem trivial to me too. If those are the only direct lines from spike, I don't think we need to include Spke license.

**Comment by fw-brice** [comment]
@lazyparser, so I don't think we imported any files directly, such that we could just add the license into a subdirectory. I think there were just a small number of things that were based on the Spike code. The majority of the simulator was based on the MIPS64 simulator in v8.

**Comment by fw-brice** [comment]
I just realized that in simulator-riscv64.cc, we already include the Spike copyright comment. I'm trying to determine how much code in that file is from Spike. It should not be a problem, since the licenses appear to be compatible.

**Comment by fw-brice** [comment]
Oh! It's already in the .h file as well 🤦 . I will just remove the TODO.
