### ISSUE TITLE
Improve CI by caching setup steps

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#32]
The CI job currently spends a lot of time on setup which is unimportant in testing the code. This should be cached. See this documentation for improving the configuration - https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows

**Comment by penguinwu** [comment]
@fw-brice Is this one still valid? If not, please close

**Comment by fw-brice** [comment]
This may still be valid, though I am not sure if any caching makes sense. I will leave it open for now to discuss speeding up the jobs since our biggest problem currently with this is the time to run the build.

**Comment by penguinwu** [comment]
@fw-brice Now that we do not use github actions, do we still need this?

**Comment by lazyparser** [comment]
IMO it is nolonger  necessary.

**Comment by fw-brice** [comment]
Correct.
