### ISSUE TITLE
Add instructions on cross-compiled build to the wiki

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#33]
Please add the build instructions [here](https://github.com/v8-riscv/v8/wiki/Cross-compiled-Build). 

Since this is work in progress, please also update the latest testing status for cross-compiled build on https://github.com/v8-riscv/v8/wiki/Testing-Status

**Comment by luyahan** [comment]
I complete it ~

**Comment by lazyparser** [comment]
> I complete it ~

good job. Currently I have not the perm to reassign the issue, maybe @fw-brice would like to help reassign this issue :-)

and a few comments:

1. the PLCT Mirror is used for the developers inside mainland China who has trouble to download fedora and v8. for general worldwide it is ok to use the original URL. Maybe we should swap these two links, putting original/upstream link as the default link, and give PLCT mirror for convinence.
2. the QEMU download & run script is fairly simple, it is better to just paste the script in to wiki.

**Comment by penguinwu** [comment]
@fw-brice Could you try out the instruction and reproduce the build on our side and add perhaps simplified instructions for people outside China?

**Comment by fw-brice** [comment]
Ok, I will try it this afternoon.

**Comment by fw-brice** [comment]
@luyahan, the changes say "please modify `toolprefix` of `gcc_toolchain("riscv64")` in `./build/toolchain/linux/BUILD.gn`, but there is no `gcc_toolchain("riscv64")` in that file. Is there an update to the build.patch that goes along with these instructions?

**Comment by fw-brice** [comment]
I ran into this error:

```
ERROR at //build/config/linux/pkg_config.gni:103:17: Script returned non-zero exit code.
    pkgresult = exec_script(pkg_config_script, args, "value")
                ^----------
Current dir: /home/brice/v8/v8/out/riscv64.native.debug/
Command: python /home/brice/v8/v8/build/config/linux/pkg-config.py glib-2.0 gmodule-2.0 gobject-2.0 gthread-2.0
Returned 1.
stderr:

Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
Package gmodule-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gmodule-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gmodule-2.0' found
Package gobject-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gobject-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gobject-2.0' found
Package gthread-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gthread-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gthread-2.0' found
Could not run pkg-config.

See //build/config/linux/BUILD.gn:89:3: whence it was called.
  pkg_config("glib") {
  ^-------------------
See //build/config/compiler/BUILD.gn:255:18: which caused the file to be included.
    configs += [ "//build/config/linux:compiler" ]
                 ^------------------------------
```

Am I supposed to add a dir to `PKG_CONFIG_PATH`?

**Comment by luyahan** [comment]
> @luyahan, the changes say "please modify `toolprefix` of `gcc_toolchain("riscv64")` in `./build/toolchain/linux/BUILD.gn`, but there is no `gcc_toolchain("riscv64")` in that file. Is there an update to the build.patch that goes along with these instructions?

Sorry, i don't add `apply build.patch` to wiki. It is neccessary for cross compiled.
I have add it.

**Comment by fw-brice** [comment]
I think you had the directions there previously to apply the patch, but I removed it because that is already covered in the "Get the source" page. The problem, I think, was that I must not have had the updated version of that file which added this section. I have resolved that, but I still get the same issue about the `PKG_CONFIG_PATH`.

**Comment by fw-brice** [comment]
@luyahan - I am still running into the pkg-config issues. What am I missing there?

**Comment by luyahan** [comment]
> @luyahan - I am still running into the pkg-config issues. What am I missing there?

It should be to install some dependencies, you can use a script written by Google.
Try `./build/install-build-deps.sh`.

**Comment by fw-brice** [comment]
Thanks Yahan. I decided to wipe everything and start clean and it works now. I am going through the rest of the steps, then will test the Node.js build.

**Comment by fw-brice** [comment]
Should we change the default prefix inside `build.patch` to `riscv64-unknown-linux-gnu`?

**Comment by fw-brice** [comment]
I have updated the instructions a bit and verified that it works for me. Thanks @luyahan! 👍
