### ISSUE TITLE
[CI] Integrate real board Hifive Unleased into our CI system.

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#36]
The PLCT lab has two Hifive boards. I'd try to integrate real board Hifive Unleased into our CI system.

**Comment by lazyparser** [comment]
status update:

currently manually tested on main branch. as the security recommendations from github, we've decide not to integrate the board directly in to github CI.

**Comment by penguinwu** [comment]
Ok. Let's close this one.

**Comment by lazyparser** [comment]
Now we have integrate the QEMU and Hifive Unleashed for merged/landed code.

They are behind the github, which means they only build commits that had been reviewed and merged.
