### ISSUE TITLE
Use of fence.i vs __builtin__clear_cache

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#370]
In 9c16a032038b1ded389995feb1160d9b4b9424df, Palmer explained that we should not use `fence.i` in user space, then in b7f01edc0a577c77c6eedd94df20bc9215aaffae reverted back to `fence.i` after seeing this change cause an error in hardware. Let's figure out for sure what is correct and remove the FIXME.

CC @palmer-dabbelt
CC @luyahan

**Comment by palmer-dabbelt** [comment]
So there's really two different things going on here, and they're both messy:

* `fence.i` was removed from the I base ISA at some point, which means it's technically not usable from userspace.  We take advantage of this assumption in the Linux implementation to avoid some unnecessary fences on thread transitions, but there's no way to prevent userspace from issuing their own fences.  As a result we currently just ask that userspace doesn't do a `fence.i` (aside from the one in the VDSO, but that's owned by the kernel).  The current kernel fencing scheme will subtly break userspace that does their own `fence.i`s, but my guess is that's subtle enough that we don't really run into those issues as this port is in the early stages.
* There may be some sort of hardware bug.  I'm generally in favor of working around those where possible, but only for hardware that ships in interesting quantities and only when we have a concrete description of that bug.  That usually means an errata in a datasheet, so if you have one of those we can discuss how we might go about working around the hardware bug.  We'll definitely need something more concrete than "doesn`t work yet".

IMHO there's way bigger problems with this port than things like this, and while we should of course get this sorted out before merging the port upstream it's probably better to sort the other stuff out first.  We'll probably have more clarity on `fence.i` as more hardware comes out, so at that point this may just sort itself out -- I think it's likely that we end up backpedaling on that kernel interface, as without a way to enforce that userspace doesn't do their own `fence.i`s they'll just sneak in and we'll end up with a bunch of subtle brokenness.

All this really depends on the timeline for getting this upstream, though: we probably won't notice this level of brokenness until someone starts to take the RISC-V stuff seriously, and I doubt that will happen any time this year ;).
