### ISSUE TITLE
[RFC] Should We have a developer meeting weekly or biweekly?

### ISSUE THREAD

**Issue by lazyparser** [v8-riscv/v8#39]
Hi all,

as now we are united as one community, I think it is a good idea to have a open meeting every two weeks.

I see Firefox dev community and RISC-V LLVM ports follows this style. Maybe we can have a try?

**Comment by penguinwu** [comment]
I like the idea of setting up a bi-weekly open developers' meeting. I will set it up this week and we can gradually improve the process.

**Comment by lazyparser** [comment]
Great 🎉

**Comment by penguinwu** [comment]
Bi-weekly developer meeting added to wiki Home. First meeting is scheduled on 07/22 (US).
