### ISSUE TITLE
Update latency estimate in instruction-scheduler-riscv64.cc

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#4]
This file was still using MIPS64 instruction scheduler latency estimate. Need to be updated to reflect latency of RISCV mapping. Also need to update `enum Latency` to use RISCV names.

**Comment by lazyparser** [comment]
Is anyone working on this bug?
if not, @thomasyonug @LOGQTAINIA would you have time to dig into it?

**Comment by LOGQTAINIA** [comment]
May I have a try when I finish #97 ?

**Comment by lazyparser** [comment]
> May I have a try when I finish #97 ?

sure. assigned.

**Comment by penguinwu** [comment]
Let's hold this one off for a bit. The latency estimates depends on the implementation in macro-assembler. Let me finish the macro-assembler cleanup (#2, #3) in a week or so, then @LOGQTAINIA can work on this one.

**Comment by penguinwu** [comment]
Duplicate of #158. @LOGQTAINIA #158 is assigned to @thomasyonug 12 days ago, since this one is assigned a while back, I will close it. If you want to work on this issue, please coordinate with @thomasyonug
