### ISSUE TITLE
New failure under 'rebase-to-master' branch

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#401]
**Describe the bug**
The test `intl/general/grandfathered_tags_without_preferred_value` fails.

**To Reproduce**
1. Checkout rebase-to-master:
   ```
   git checkout rebase-to-master
   ```
2. Build:
   ```
   ./tools/dev/gm.py riscv64.debug.all
   ```
3. Run test:
   ```
   out/riscv64.debug/d8 --test test/intl/assert.js test/intl/utils.js test/intl/general/grandfathered_tags_without_preferred_value.js --random-seed=916062903 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --allow-natives-syntax
   ```

**Expected behavior**
All tests should pass

**Errors/Logs**
```
/home/brice/v8/v8/test/intl/assert.js:105: Error: Failure: expected <xtg>, found <xtg-x-cel-gaulish>.
  throw new Error(message);
  ^
Error: Failure: expected <xtg>, found <xtg-x-cel-gaulish>.
    at fail (/home/brice/v8/v8/test/intl/assert.js:105:9)
    at assertEquals (/home/brice/v8/v8/test/intl/assert.js:114:5)
    at /home/brice/v8/v8/test/intl/general/grandfathered_tags_without_preferred_value.js:16:3
    at Array.forEach (<anonymous>)
    at /home/brice/v8/v8/test/intl/general/grandfathered_tags_without_preferred_value.js:13:3
```

**Comment by fw-brice** [comment]
This test passed on the [CI job](https://8961001f3fcb.ngrok.io/logs/393-run-2021-01-19T15:30:01.733Z.log), so it may just be an issue with my environment. Can someone else confirm?

**Comment by lazyparser** [comment]
@qjivy @luyahan pls check it. at a high priority.

**Comment by qjivy** [comment]
> This test passed on the [CI job](https://8961001f3fcb.ngrok.io/logs/393-run-2021-01-19T15:30:01.733Z.log), so it may just be an issue with my environment. Can someone else confirm?

My native run is pass.

**Comment by fw-brice** [comment]
Ok, thanks for checking. I will close this.
