### ISSUE TITLE
Review Simulator::FMaxMinHelper

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#432]
I removed an unclear FIXME from this function for upstreaming.

```cpp
template <typename T>
T Simulator::FMaxMinHelper(T a, T b, MaxMinKind kind) {
  // set invalid bit for signaling nan
  if ((a == std::numeric_limits<T>::signaling_NaN()) ||
      (b == std::numeric_limits<T>::signaling_NaN())) {
    // FIXME: NV -> kInvalidOperation
    set_csr_bits(csr_fflags, kInvalidOperation);
  }
```

**Comment by qjivy** [comment]
The semantic of the FMaxMinHelper is exactly correct according to the ISA-SPEC, and the "set_csr_bits(csr_fflags, kInvalidOperation); " is equal to  "set_fflags(flags) { set_csr_bits(csr_fflags, flags);" 

So the code is all right here. We can close this issue.
