### ISSUE TITLE
Segmentation fault occurs when run test-macro-assembler-riscv64/LoadAddress on qemu or hifive unleashed

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#49]
![image](https://user-images.githubusercontent.com/22358871/88053015-bd00e080-cb8d-11ea-8955-61dbdadd3cd1.png)

if i delete `__ nop();`   

![image](https://user-images.githubusercontent.com/22358871/88052806-65fb0b80-cb8d-11ea-962b-9537f306fb03.png)

code is here: https://github.com/v8-riscv/v8/blob/riscv-porting-dev/test/cctest/test-macro-assembler-riscv64.cc#L115

**Comment by fw-brice** [comment]
This test was copied from MIPS64. I do not see any reason why the nops need to be there in RISC-V, but I also don't see any reason why they should cause a seg fault. Are you saying the the seg fault occurs when the nop is executed?

The sequence of instructions executed by the simulator is:

```
  0x00a5c7a02040   00056733       or        a4, a0, zero_reg      0000000000000000    (1)    int64:0 uint64:0
  0x00a5c7a02044   0140006f       j         20                    0000000000000000    (2)    int64:0 uint64:0
  0x00a5c7a02058   00000737       lui       a4, 0x0               0000000000000000    (3)    int64:0 uint64:0
  0x00a5c7a0205c   55b7071b       addiw     a4, a4, 1371          000000000000055b    (4)    int64:1371 uint64:1371
  0x00a5c7a02060   00c71713       slli      a4, a4, 12            000000000055b000    (5)    int64:5615616 uint64:5615616
  0x00a5c7a02064   78c70713       addi      a4, a4, 1932          000000000055b78c    (6)    int64:5617548 uint64:5617548
  0x00a5c7a02068   00c71713       slli      a4, a4, 12            000000055b78c000    (7)    int64:23009476608 uint64:23009476608
  0x00a5c7a0206c   16670713       addi      a4, a4, 358           000000055b78c166    (8)    int64:23009476966 uint64:23009476966
  0x00a5c7a02070   00c71713       slli      a4, a4, 12            000055b78c166000    (9)    int64:94246817652736 uint64:94246817652736
  0x00a5c7a02074   a6870713       addi      a4, a4, -1432         000055b78c165a68    (10)    int64:94246817651304 uint64:94246817651304
  0x00a5c7a02078   00070067       jr        a4                    0000000000000000    (11)    int64:0 uint64:0
  0x55b78c165a68   00000013       nop                             0000000000000000    (12)    int64:0 uint64:0
  0x55b78c165a6c   00000013       nop                             0000000000000000    (13)    int64:0 uint64:0
  0x55b78c165a70   00008067       ret                             0000000000000000    (14)    int64:0 uint64:0
```

**Comment by luyahan** [comment]
> This test was copied from MIPS64. I do not see any reason why the nops need to be there in RISC-V, but I also don't see any reason why they should cause a seg fault. Are you saying the the seg fault occurs when the nop is executed?
> 
> The sequence of instructions executed by the simulator is:
> 
> ```
>   0x00a5c7a02040   00056733       or        a4, a0, zero_reg      0000000000000000    (1)    int64:0 uint64:0
>   0x00a5c7a02044   0140006f       j         20                    0000000000000000    (2)    int64:0 uint64:0
>   0x00a5c7a02058   00000737       lui       a4, 0x0               0000000000000000    (3)    int64:0 uint64:0
>   0x00a5c7a0205c   55b7071b       addiw     a4, a4, 1371          000000000000055b    (4)    int64:1371 uint64:1371
>   0x00a5c7a02060   00c71713       slli      a4, a4, 12            000000000055b000    (5)    int64:5615616 uint64:5615616
>   0x00a5c7a02064   78c70713       addi      a4, a4, 1932          000000000055b78c    (6)    int64:5617548 uint64:5617548
>   0x00a5c7a02068   00c71713       slli      a4, a4, 12            000000055b78c000    (7)    int64:23009476608 uint64:23009476608
>   0x00a5c7a0206c   16670713       addi      a4, a4, 358           000000055b78c166    (8)    int64:23009476966 uint64:23009476966
>   0x00a5c7a02070   00c71713       slli      a4, a4, 12            000055b78c166000    (9)    int64:94246817652736 uint64:94246817652736
>   0x00a5c7a02074   a6870713       addi      a4, a4, -1432         000055b78c165a68    (10)    int64:94246817651304 uint64:94246817651304
>   0x00a5c7a02078   00070067       jr        a4                    0000000000000000    (11)    int64:0 uint64:0
>   0x55b78c165a68   00000013       nop                             0000000000000000    (12)    int64:0 uint64:0
>   0x55b78c165a6c   00000013       nop                             0000000000000000    (13)    int64:0 uint64:0
>   0x55b78c165a70   00008067       ret                             0000000000000000    (14)    int64:0 uint64:0
> ```

Yes, when excute nop  in qemu, it occurs the  segfault ,but when i remove`__nop()` after `Branch`, it occurs seg fault on `ret`. It has nothing to do with the instruction itself.
In my opinion ，whether they are related to memory reading and writing. These instruction sequences are generated at runtime.

**Comment by fw-brice** [comment]
Ok, so that sounds like it is jumping to a bad address, but the sequence of instructions generating the target address in a4 seems correct and the resulting value in a4 looks correct (if I am understanding your picture correctly). There is no load involved in the nop instruction, so the only load is the instruction fetch. I am not sure what could be going wrong there.

**Comment by fw-brice** [comment]
Peng noticed that in the simulated trace, it is strange that the jump address calculated in `a4` is not the expected PC, based on the address of the starting point, of 0x0x00a5c7a02048, but instead it is some far away address, 0x55b78c165a68.

In reviewing the simulated execution, I see that the 0x55b7... address is the expected address, when the code is originally generated. This means that the block of code must have been relocated before execution, but this relocation did not update the instructions loading the address.

I am now looking into where that relocation happens and why it has not properly relocated the load address sequence. I have a suspicion that whatever that code is, it may be looking for the MIPS load address sequence instead of the new RISC-V sequence.

**Comment by luyahan** [comment]
@fw-brice Do you mean  the relocation doesn't be excuted correctly on Qemu ? 
I have a question about why  a reloaction to update the instructions loading the address is needed ?

**Comment by luyahan** [comment]
```
0x5618e8b81ae0: 00056733       or        a4, a0, zero_reg
branch_offset_helper: 0x7ffcb6832060 to 0x5618e8b81ae4 (4)
	started link
0x5618e8b81ae4: 0000006f       j         0 -> 0x7ffcb6831c14
binding 8 to label 0x7ffcb6832068
0x5618e8b81ae8: 00000013       nop
0x5618e8b81aec: 00000013       nop
0x5618e8b81af0: 00008067       ret
0x5618e8b81af4: 00000013       nop
binding 24 to label 0x7ffcb6832060
target_at: 0x5618e8b81ae4 (4)
	0000006f       j         0 -> 0x7ffcb6831c64
	fixup: 4 to 20
target_at_put: 0x5618e8b81ae4 (4) to 0x5618e8b81af8 (24)
0140006f       j         20 -> 0x7ffcb6831cd8
jump_address: 0x7ffcb6832068 to 0x5618e8b81af8 (24)
li_constant(14, 5618e8b81ae8 <94664983583464>)
0x5618e8b81af8: 00000737       lui       a4, 0x0
0x5618e8b81afc: 5627071b       addiw     a4, a4, 1378
0x5618e8b81b00: 00c71713       slli      a4, a4, 12
0x5618e8b81b04: 8e970713       addi      a4, a4, -1815
0x5618e8b81b08: 00c71713       slli      a4, a4, 12
0x5618e8b81b0c: b8270713       addi      a4, a4, -1150
0x5618e8b81b10: 00c71713       slli      a4, a4, 12
0x5618e8b81b14: ae870713       addi      a4, a4, -1304
0x5618e8b81b18: 00070067       jr        a4
0x5618e8b81b1c: 00000013       nop
0x5618e8b81b20: 00100073       ebreak
0x5618e8b81b24: 0007f037       lui       zero_reg, 0x7f
0x5618e8b81b28: 00100073       ebreak
0x5618e8b81b2c: 0007f037       lui       zero_reg, 0x7f
0x5618e8b81b30: 00100073       ebreak
0x5618e8b81b34: 0007f037       lui       zero_reg, 0x7f
0x5618e8b81b38: 00100073       ebreak
0x5618e8b81b3c: 0007f037       lui       zero_reg, 0x7f
0x5618e8b81b40: 00100073       ebreak
0x5618e8b81b44: 0007f037       lui       zero_reg, 0x7f
```
i add `--debug-riscv`, find that address starts with 0x5618XXX at first.

**Comment by luyahan** [comment]
```
(gdb) x /20i 0x3fee582044
   0x3fee582044:        or      a4,a0,zero
   0x3fee582048:        j       0x3fee58205c
   0x3fee58204c:        nop
   0x3fee582050:        nop
   0x3fee582054:        ret
   0x3fee582058:        nop
   0x3fee58205c:        lui     a4,0x0
   0x3fee582060:        addiw   a4,a4,3
   0x3fee582064:        slli    a4,a4,0xc
   0x3fee582068:        addi    a4,a4,-1361
   0x3fee58206c:        slli    a4,a4,0xc
   0x3fee582070:        addi    a4,a4,760
   0x3fee582074:        slli    a4,a4,0xc
   0x3fee582078:        addi    a4,a4,2012
=> 0x3fee58207c:        jr      a4
   0x3fee582080:        nop
   0x3fee582084:        ebreak
   0x3fee582088:        lui     zero,0x54321
   0x3fee58208c:        ebreak
   0x3fee582090:        lui     zero,0x54321
(gdb) info registers a4
a4             0x2aaf2f87dc     183327754204
(gdb) x /20i 0x2aaf2f87dc
   0x2aaf2f87dc:        nop
   0x2aaf2f87e0:        nop
   0x2aaf2f87e4:        ret
   0x2aaf2f87e8:        nop
   0x2aaf2f87ec:        lui     a4,0x0
   0x2aaf2f87f0:        addiw   a4,a4,3
   0x2aaf2f87f4:        slli    a4,a4,0xc
   0x2aaf2f87f8:        addi    a4,a4,-1361
   0x2aaf2f87fc:        slli    a4,a4,0xc
   0x2aaf2f8800:        addi    a4,a4,760
   0x2aaf2f8804:        slli    a4,a4,0xc
   0x2aaf2f8808:        addi    a4,a4,2012
   0x2aaf2f880c:        jr      a4
   0x2aaf2f8810:        nop
   0x2aaf2f8814:        ebreak
   0x2aaf2f8818:        lui     zero,0x54321
   0x2aaf2f881c:        ebreak
   0x2aaf2f8820:        lui     zero,0x54321
   0x2aaf2f8824:        ebreak
   0x2aaf2f8828:        lui     zero,0x54321
```
In actual operation, the address has been moved, but the jump address is still the same.

**Comment by luyahan** [comment]
So we need add a relocinfo when load a label or modify test case  that jump a label by offset.

**Comment by fw-brice** [comment]
I'm not sure yet. I am looking into it now. It is clear that there is a discrepancy between the two versions, but I don't know why yet.

**Comment by fw-brice** [comment]
> In actual operation, the address has been moved, but the jump address is still the same.

Yes, that seems to be the problem. With your initial description, I thought that this was not happening in the run on QEMU, but it seems that it is. I am looking into where this relocation should happen and why it is not.

**Comment by fw-brice** [comment]
I believe the relocation happens in `Factory::CodeBuilder::CodeBuilder(Isolate* isolate, const CodeDesc& desc, Code::Kind kind)`, at src/heap/factory.cc:197:

```
    // Migrate generated code.
    // The generated code can contain embedded objects (typically from handles)
    // in a pointer-to-tagged-value format (i.e. with indirection like a handle)
    // that are dereferenced during the copy to point directly to the actual
    // heap objects. These pointers can include references to the code object
    // itself, through the self_reference parameter.
    code->CopyFromNoFlush(heap, code_desc_);
```

I think you're right that we need to insert a reloc for the `LoadAddress`. I am experiimenting with it now.

**Comment by fw-brice** [comment]
I do not have a working solution yet, but my work pushed to the branch `49-reloc`, in case you continue work on it during my night time.

**Comment by luyahan** [comment]
int Assembler::RelocateInternalReference not implemented for riscv64.

**Comment by luyahan** [comment]
I implement reloc address in #66
