### ISSUE TITLE
Enable `stop`, `break`, and `gdb` commands in the debugger in the RISCV simulator

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#5]
Currently the built-in debugger ini the built-in riscv simulator (i.e., `simulator-riscv64.cc` does not yet support `stop`, `break`, `gdb` commands yet.

For `stop` and `break`, the problem seems to be that we cannot instructions in the generated code buffer to special `ebreak` or `stop` instruction due to some access permission issues.

`gdb` command is not yet supported because we need to understand better of the riscv gdb interface w/ native codes.

**Comment by LOGQTAINIA** [comment]
This issue could be closed.

**Comment by LOGQTAINIA** [comment]
I will update the debugging instructions in wiki soon.

**Comment by penguinwu** [comment]
Are we able to support `gdb` command inside the simulator debugger?

**Comment by LOGQTAINIA** [comment]
> 
> 
> Are we able to support `gdb` command inside the simulator debugger?

Yeah, `gdb` command is enabled.

More info here: #93

**Comment by penguinwu** [comment]
Thanks @LOGQTAINIA , great work!

**Comment by LOGQTAINIA** [comment]
Thank you for your patience and help all the time.
