### ISSUE TITLE
Internal error: unimplemented code in diagnostics/perf-jit.h

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#57]
**Describe the bug**
Testcase triggers unimplemented code in `src/diagnostics/perf-jit.h`

**To Reproduce**
1. Use simulated debug build (see instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build))
2. Run test/program
```
out/riscv64.sim/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/wasm/regress-1032753.js --random-seed=-812327453 --nohard-abort --enable-slow-asserts --verify-heap --testing-d8-test-runner --perf-prof --perf-prof-delete-file
```
```
#
# Fatal error in ../../src/diagnostics/perf-jit.h, line 105
# unimplemented code
#
```

**Expected behavior**
No error message if test passes

**Additional context**
None

**Comment by lazyparser** [comment]
@LOGQTAINIA have a try
