### ISSUE TITLE
Enable fuzzer test cases

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#6]
`tools/run-tests.py --outdir=out.gn/mips64el.debug/ fuzzer` does not run any tests. 

There probably requires some setup to enable the fuzzer tests.

There is a bunch of buzzers under `out/riscv/v8_simple_xxx_fuzzer`. Please take a look at those too.

**Comment by thomasyonug** [comment]
Actually, this is a testrunner bug from upstream.

[https://bugs.chromium.org/p/v8/issues/detail?id=10770](url)

We can now ignore fuzzer testing until it's fixed.
