### ISSUE TITLE
Testing for release simulated build

### ISSUE THREAD

**Issue by penguinwu** [v8-riscv/v8#63]
Description:

- Built a simulated release build (see https://v8.dev/docs/build, something like `tools/dev/gm.py riscv64.release`, but you may need to add riscv64/32 target to gm.py)
- Run all test suites 
- Triage new failures (compared to simulated debug build) and open issues

Update build wiki (https://github.com/v8-riscv/v8/wiki/simulator-build):
- Add instructions on how to build release build;
- And instructions on how to build with `gm.py`

**Comment by derekzTu** [comment]
Build wiki update: https://github.com/v8-riscv/v8/wiki/Simulator-Build#build-v8-release-simulated-build

**Comment by derekzTu** [comment]
Testing Status wiki update: https://github.com/v8-riscv/v8/wiki/Testing-Status#release-build-v8-riscv-testing
