### ISSUE TITLE
RV32 backend

### ISSUE THREAD

**Issue by chaoRIOS** [v8-riscv/v8#68]
Dev branch:

- [rv32](https://github.com/chaoRIOS/v8/tree/rv32)

Status:

- RV32 simulator
- RV32IM cctests

TODO:

- RV32 compiler
- RV32A
- re-enabling RV64 testcases

**Comment by penguinwu** [comment]
This feature is too big to be done in one issue. Close it for now. If we decide to move forward w/ 32-bit, will open smaller individual issues for the feature.
