### ISSUE TITLE
internal error: cctest/test-run-wasm-64.cc:753 821

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#74]
**Describe the bug**
Run test case failed

**To Reproduce**
1. Build with options 'riscv64.native.release'
2. Run test/program 'python2 ./tools/run-tests.py --outdir=./ cctest' on `hifive unleashed`
3. See error

**Expected behavior**
not error occurs

**Errors/Logs**
```
=== cctest/test-run-wasm-64/RunWasmLiftoff_I64SConvertSatF32 ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-64.cc, line 753
# Check failed: expected == found (-9223372036854775808 vs. 9223372036854775807).
#
#
#
#FailureMessage Object: 0x3fffa7f928
=== cctest/test-run-wasm-64/RunWasmLiftoff_I64UConvertSatF32 ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-64.cc, line 821
# Check failed: expected == found (0 vs. 18446744073709551615).
#
#
#
#FailureMessage Object: 0x3fff8eb928
=== cctest/test-run-wasm-64/RunWasmTurbofan_I64SConvertSatF32 ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-64.cc, line 753
# Check failed: expected == found (-9223372036854775808 vs. 9223372036854775807).
#
#
#
#FailureMessage Object: 0x3fffdab928
=== cctest/test-run-wasm-64/RunWasmTurbofan_I64UConvertSatF32 ===
#
# Fatal error in ../../test/cctest/wasm/test-run-wasm-64.cc, line 821
# Check failed: expected == found (0 vs. 18446744073709551615).
#
#
#
#FailureMessage Object: 0x3fff825928
```

**Additional context**

**Comment by luyahan** [comment]
I am working on it .

**Comment by luyahan** [comment]
```
(gdb) x /20i 0x0000003ff7ffc5e8
   0x3ff7ffc5e8:        ebreak
   0x3ff7ffc5ec:        frflags a2
   0x3ff7ffc5f0:        andi    a2,a2,16
   0x3ff7ffc5f4:        seqz    a2,a2
   0x3ff7ffc5f8:        fsflags t3
   0x3ff7ffc5fc:        li      t3,0
   0x3ff7ffc600:        beq     a2,t3,0x3ff7ffc61c
   0x3ff7ffc604:        mv      a0,a1
   0x3ff7ffc608:        mv      sp,s0
   0x3ff7ffc60c:        ld      s0,0(sp)
   0x3ff7ffc610:        ld      ra,8(sp)
   0x3ff7ffc614:        addi    sp,sp,16
   0x3ff7ffc618:        ret
   0x3ff7ffc61c:        feq.s   s3,fa0,fa0
   0x3ff7ffc620:        beqz    s3,0x3ff7ffc64c
   0x3ff7ffc624:        fmv.d.x fs9,zero
=> 0x3ff7ffc628:        flt.s   s3,fa0,fs9
   0x3ff7ffc62c:        bnez    s3,0x3ff7ffc640
   0x3ff7ffc630:        li      a1,-1
   0x3ff7ffc634:        slli    a1,a1,0x3f
(gdb) info registers fa0
fa0            {float = -inf, double = -nan(0xfffffff800000)}   (raw 0xffffffffff800000)
(gdb) info registers fs9
fs9            {float = 0, double = 0}  (raw 0x0000000000000000)
(gdb) si
0x0000003ff7ffc62c in ?? ()
(gdb) p s3
No symbol "s3" in current context.
(gdb) info registers s3
s3             0x0      0
(gdb) x /20i 0x0000003ff7ffc5e8
```

**Comment by luyahan** [comment]
(gdb) info registers s3
s3             0x55     85
(gdb) x /20i 0x3ff7ffc628
=> 0x3ff7ffc628:        flt.s   s3,fa0,fs9
   0x3ff7ffc62c:        bnez    s3,0x3ff7ffc640
   0x3ff7ffc630:        li      a1,-1
   0x3ff7ffc634:        slli    a1,a1,0x3f
   0x3ff7ffc638:        addi    a1,a1,-1
   0x3ff7ffc63c:        j       0x3ff7ffc604
   0x3ff7ffc640:        li      a1,-1
   0x3ff7ffc644:        slli    a1,a1,0x3f
   0x3ff7ffc648:        j       0x3ff7ffc604
   0x3ff7ffc64c:        li      a1,0
   0x3ff7ffc650:        j       0x3ff7ffc604
   0x3ff7ffc654:        nop
   0x3ff7ffc658:        unimp
   0x3ff7ffc65a:        unimp
   0x3ff7ffc65c:        nop
   0x3ff7ffc65e:        unimp
   0x3ff7ffc660:        unimp
   0x3ff7ffc662:        unimp
   0x3ff7ffc664:        unimp
   0x3ff7ffc666:        unimp
(gdb) info registers fa0
fa0            {float = -inf, double = -nan(0xfffffff800000)}   (raw 0xffffffffff800000)
(gdb) info registers fs9
fs9            {float = 0, double = 0}  (raw 0x0000000000000000)
(gdb) si
0x0000003ff7ffc62c in ?? ()
(gdb) info registers s3
s3             0x0      0

**Comment by luyahan** [comment]
I run this case in qemu. It's ok  but incorrect in hifive unleashed

**Comment by fw-brice** [comment]
The documentation about FEQ.S, FLT.S, and FLE.S states:

> For all three instructions, the result is 0 if either operand is NaN.

**Comment by luyahan** [comment]
> The documentation about FEQ.S, FLT.S, and FLE.S states:
> 
> > For all three instructions, the result is 0 if either operand is NaN.

But the operand is inf not NaN.And i write a sample code, the result is right in hifive.

**Comment by fw-brice** [comment]
Oh right. Sorry, I read that too quickly 😬

**Comment by luyahan** [comment]
> The documentation about FEQ.S, FLT.S, and FLE.S states:
> 
> > For all three instructions, the result is 0 if either operand is NaN.

I got it, fs9 is NaN. So the zero set incorrtectly.

**Comment by luyahan** [comment]
> Oh right. Sorry, I read that too quickly 😬 

Gdb bug in fs9, It's NaN not zero.

**Comment by luyahan** [comment]
@fw-brice  refer to https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/mfGw77uQYwc/m/1IrLgMpWAwAJ
