### ISSUE TITLE
Attempting to Kill Process for certain tests in cctest

### ISSUE THREAD

**Issue by derekzTu** [v8-riscv/v8#88]
**Describe the bug**
Trying to run some tests on the release build causes an attempt to kill of some tests, which can result in hanging

**To Reproduce**
1. Build release build (see instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build))
2. Run program:
```bash
 out/riscv64.release/cctest test-interpreter/InterpreterStringComparisons --random-seed=1676373137 --nohard-abort --testing-d8-test-runner
```
3. See error
If run individually it hangs, if run in the test suite it looks like this:

```bash
Attempting to kill process 69429 started as:
 out/riscv64.release/cctest test-interpreter/InterpreterStringComparisons --random-seed=1676373137 --nohard-abort --testing-d8-test-runner
```

**Expected behavior**
Should not try to attempt to kill process.

**Additional context**
These are additional tests that also run into the same issue:

Test:
`test-run-bytecode-graph-builder/BytecodeGraphBuilderCompare`

Command:
```bash
  out/riscv64.release/cctest test-run-bytecode-graph-builder/BytecodeGraphBuilderCompare --random-seed=1676373137 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test-run-jsops/BinopGreaterThanOrEqual`

Command:
```bash
  out/riscv64.release/cctest test-run-jsops/BinopGreaterThanOrEqual --random-seed=1676373137 --nohard-abort --testing-d8-test-runner
```

-------
Test:
`test-run-jsops/BinopGreaterThan`

Command:
```bash
  out/riscv64.release/cctest test-run-jsops/BinopGreaterThan --random-seed=1676373137 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test-run-jsbranches/ForStatement`

Command:
```bash
out/riscv64.release/cctest test-run-jsbranches/ForStatement --random-seed=-356107759 --nohard-abort --testing-d8-test-runner
```

-------
Test:
`test-run-jsbranches/WhileStatement`

Command:
```bash
out/riscv64.release/cctest test-run-jsbranches/WhileStatement --random-seed=-356107759 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test-run-jsops/BinopLessThan`

Command:
```bash
out/riscv64.release/cctest test-run-jsops/BinopLessThan --random-seed=-356107759 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test-run-jsops/BinopLessThanOrEqual`

Command:
```bash
out/riscv64.release/cctest test-run-jsops/BinopLessThanOrEqual --random-seed=-356107759 --nohard-abort --testing-d8-test-runner
```
When running these tests individually, they seem to hang.

**Comment by fw-brice** [comment]
This seems to be caused by the same issue as #89.
