### ISSUE TITLE
Attempting to Kill Process for certain tests in mjsunit

### ISSUE THREAD

**Issue by derekzTu** [v8-riscv/v8#89]
**Describe the bug**
Trying to run some tests on the release build causes an attempt to kill of some tests, which can result in hanging

**To Reproduce**
1. Build release build (see instructions [here](https://github.com/v8-riscv/v8/wiki/simulator-build))
2. Run program:
```bash
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/array-sort.js --random-seed=703802079 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
3. See error
If run individually it hangs, if run in the test suite it looks like this:

```bash
Attempting to kill process 99638 started as:
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/array-sort.js --random-seed=703802079 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```

**Expected behavior**
Does not attempt to kill process or hang

**Additional context**
These are additional tests that also have this issue

Test:
`test/mjsunit/compare-character.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-character.js --random-seed=703802079 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test/mjsunit/compare-known-objects-slow.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-known-objects-slow.js --random-seed=703802079 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/compare-objects.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-objects.js --random-seed=-1781004596 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/compare-known-objects.js`

Command:
```bash
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-known-objects.js --random-seed=675030927 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/compare-table-gt.js `

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-table-gt.js --random-seed=-1781004596 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test/mjsunit/compare-table-gteq.js `

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-table-gteq.js --random-seed=-1781004596 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test/mjsunit/compare-table-lt.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-table-lt.js --random-seed=675030927 --nohard-abort --testing-d8-test-runner
```

-------
Test:
`test/mjsunit/compare-table-lteq.js`

Command:
```bash
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compare-table-lteq.js --random-seed=675030927 --nohard-abort --testing-d8-test-runner
```

-------
Test:
`test/mjsunit/const-field-tracking.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/const-field-tracking.js --random-seed=675030927 --nohard-abort --testing-d8-test-runner --allow-natives-syntax --opt --no-always-opt
```
-------
Test:
`test/mjsunit/compiler/escape-analysis-12.js`
Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compiler/escape-analysis-12.js --random-seed=-1898324121 --nohard-abort --testing-d8-test-runner --allow-natives-syntax --turbo-escape
```
-------
Test:
`test/mjsunit/compiler/escape-analysis-representation.js`

Command
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compiler/escape-analysis-representation.js --random-seed=-1898324121 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```

-------
Test:
`test/mjsunit/compiler/regress-3249650.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compiler/regress-3249650.js --random-seed=-1898324121 --nohard-abort --testing-d8-test-runner
```

-------
Test:
`test/mjsunit/compiler/string-comparison-opt.js`
Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/compiler/string-comparison-opt.js --random-seed=-1898324121 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/es6/proxies.js `

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/es6/proxies.js --random-seed=1378595886 --nohard-abort --testing-d8-test-runner --sim-stack-size=500 --allow-natives-syntax
```

-------
Test:
`test/mjsunit/regress/regress-343609.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-343609.js --random-seed=-1906467166 --nohard-abort --testing-d8-test-runner --allow-natives-syntax --block-concurrent-recompilation --expose-gc
```
------
Test:
`test/mjsunit/regress/regress-4788-2.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-4788-2.js --random-seed=-1906467166 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/regress/regress-503.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-503.js --random-seed=-1906467166 --nohard-abort --testing-d8-test-runner
```

-------
Test:
`test/mjsunit/regress/regress-897512.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-897512.js --random-seed=1635423114 --nohard-abort --testing-d8-test-runner
```
-------
Test:
`test/mjsunit/regress/regress-crbug-679202.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-crbug-679202.js --random-seed=1635423114 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/regress/regress-crbug-941743.js`

Command:
```bash
  out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-crbug-941743.js --random-seed=1635423114 --nohard-abort --testing-d8-test-runner --allow-natives-syntax --noenable-slow-asserts --nostress-opt --noalways-opt
```
-------
Test:
`test/mjsunit/regress/regress-crbug-964833.js`
Command:
```bash
out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-crbug-964833.js --random-seed=1635423114 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```
-------
Test:
`test/mjsunit/regress/regress-deopt-store-effect.js`

Command:
```bash
 out/riscv64.release/d8 --test test/mjsunit/mjsunit.js test/mjsunit/regress/regress-deopt-store-effect.js --random-seed=2024013991 --nohard-abort --testing-d8-test-runner --allow-natives-syntax
```

**Comment by penguinwu** [comment]
This error still persists using the latest in `riscv64`.

**Comment by lazyparser** [comment]
I've hit this issue on physical board, riscv64 branch. 

seems it is caused by too small timeout setting?

**Comment by fw-brice** [comment]
The hang is caused by a bad instruction generated in `StringGreaterThan`:

```
 0x5606f9fe4a20     0  00a58063       beq       a1, a0, 0 -> 0x5606f9fe4a20  (StringGreaterThan)
```
If `a1` is equal to `a0`, it branches to itself. I am looking into where this is coming from.

**Comment by fw-brice** [comment]
The bad code comes from `StringBuiltinsAssembler::GenerateStringRelationalComparison` in _builtins-string-gen.cc_.

**Comment by fw-brice** [comment]
I found the problem here and will fix it today. What is happening is that the first instruction, at position 0, in a function is a branch to a label, which is not yet bound. Then another instruction later on uses that same label, creating a chain for the later binding. When the label is bound later in the function, it loops through the chain, fixing up all of the instructions that were generated with that unbound label. The problem arises in that the special value indicating the end of the chain is 0, but the position of the first instruction is 0, so it looks like the end of the chain, rather than another instruction that needs updating. I will change the special value to something else that could not be a valid position.

**Comment by DrRezaYazdani1** [comment]
Why it works in debug build and fails in release?

**Comment by fw-brice** [comment]
> Why it works in debug build and fails in release?

In the debug build, the branch instruction is not at offset 0.

**Comment by penguinwu** [comment]
`StringBuiltinsAssembler::GenerateStringRelationalComparison` is in the common path. Is it a bug that only manifests on RISCV, or for all platforms too?

**Comment by fw-brice** [comment]
It's specific to RISC-V. It is a problem in my implementation of the label binding.

**Comment by DrRezaYazdani1** [comment]
Good catch and great detective work.

**Comment by fw-brice** [comment]
With my fix in place, one of the above tests reports an error and one still hangs. The rest run successfully.
* test/mjsunit/regress/regress-4788-2.js: Reports an error
```
test/mjsunit/regress/regress-4788-2.js:10: Invalid asm.js: Unexpected token
```
* test/mjsunit/regress/regress-crbug-941743.js: Hangs
*

**Comment by fw-brice** [comment]
test/mjsunit/regress/regress-4788-2.js passes as well, it just had the wrong flags. #246 is opened for test/mjsunit/regress/regress-crbug-941743.js.
