### ISSUE TITLE
Riscv64-simulator can't handle a  float value which isn't  NaN-boxed.

### ISSUE THREAD

**Issue by luyahan** [v8-riscv/v8#97]
**Describe the bug**
On riscv64, a float value is stored into 64-bit f-register. It should be NaN boxed, such as `zero` boxed to `0xFFFFFFFF00000000ULL`. If not boxed, it will be treated as a NaN value on hifive-unleashed. So our simulator should also treated  it as NaN.
refer https://groups.google.com/a/groups.riscv.org/g/sw-dev/c/mfGw77uQYwc/m/HhOb3QUvBAAJ
 
**To Reproduce**
relating #74 

**Expected behavior**
None

**Errors/Logs**
None

**Additional context**
None

**Comment by luyahan** [comment]
@LOGQTAINIA

**Comment by luyahan** [comment]
It also relating #61 @fw-brice @penguinwu . We don't handle correctly float-value with NaN boxing.

**Comment by penguinwu** [comment]
You are right. I didnt handle NaN-boxing in the simulator, good that you've spotted the problem. We shall probably add a test case for NaN-boxing in `test-assembler-riscv64.cc` too.

**Comment by lazyparser** [comment]
> You are right. I didnt handle NaN-boxing in the simulator, good that you've spotted the problem. We shall probably add a test case for NaN-boxing in `test-assembler-riscv64.cc` too.

if there is no issue for it, would @LOGQTAINIA open one for it and have a PR?
