### ISSUE TITLE
Add architecture flags to specify various combinations of RISC-V ISA extensions

### ISSUE THREAD

**Issue by fw-brice** [v8-riscv/v8#98]
As we add support for various extensions, we should follow the standards defined for RISC-V toolchains [here](https://github.com/riscv/riscv-toolchain-conventions). Following the same conventions and using the same flags as other tools will make it easier for the community to adopt.

Let's start with a design issue for specifying riscv architecture flag before implementation.

**Comment by lazyparser** [comment]
IIUC we are using RISCV64G or RISCV64GC currently. the `V` Extension might be added optionally for performance.

**Comment by lazyparser** [comment]
as we discussed last week, RISCV32* might not be a stable target yet.

**Comment by penguinwu** [comment]
@fw-brice Do you envision we specify target architectures as flags to build scripts (e.g., variations to `riscv64`), or do we use the C/C++ preprocessor flags (https://github.com/riscv/riscv-toolchain-conventions#cc-preprocessor-definitions) to determine which specific ISA extensions are supported by the hardware? I suppose the latter works for native build but not simulator build?

In any case, we shall start with a design issue for specifying risc-v arch-flags before the implementation. I can start an RFC on this.

**Comment by fw-brice** [comment]
I was just referring to the flags for building v8 actually.

**Comment by LOGQTAINIA** [comment]
@thomasyonug and I did some research about architecture flags in llvm-riscv and v8-mips. 

For llvm, which is a cross-compiler, it is necessary to provide -march when compiling a program. [Reference link](https://reviews.llvm.org/D69383)

For v8, which is a JIT, it is fine to provide -march only when building it, like v8-mips.

So, we suggest that we specify target architectures when building v8. And the specified flag would be transformed to macro definition in *.cpp. 

For an example, configure the build using gn

```
gn gen out.gn/riscv64_debug --args='is_debug=true target_cpu="x86" \
v8_target_cpu="riscv64" march="rv64g"
```

Using these code in BUILD.gn, we could add macro definition to *.cpp

```
if ('c' in march or 'g' in march) {
      defines += [ "__riscv_compressed" ]
```

And then, in macro-assembler, we could use those macro definition to generate corresponding instruction.

```
#ifdef __riscv_compressed
    // generate C extension instruction
#else 
    // generate 32-bit instruction
```

Also, this design works both for native build and simulator build.

**Comment by fw-brice** [comment]
Yes, this looks good to me. 👍

**Comment by penguinwu** [comment]
MIPS uses this flag to specify architecture variants, ` mips_arch_variant="r2"`. We could use a similar naming convention `riscv_arch_variant="xxx"`.

Yes, you can go ahead to implement this design.

**Comment by LOGQTAINIA** [comment]
When I was trying to implement this design, I noticed that here is no way to parse string in GN. So I have no idea to add arch flags from string like `rv64gc` in GN. 

But, for cross compile, it is possible to pass the parameter to gcc which could parse the string. And then gcc would add those flags as macro definitions. Like
```
riscv_arch_variant="xxx"
```
and
```
cflags += [ riscv_arch_variant ]
```

For simlator, it seems that we should add each extension flag if we want to enable the extension. 

```
gn gen out.gn/riscv64_debug --args='is_debug=true target_cpu="x86" \
v8_target_cpu="riscv64" c_ext=true
```
and
```
if (c_ext) {
  defines += [ "riscv_compressed" ]
}
```

So is it ok to implement this desgin which may looks a little bit silly?

**Comment by penguinwu** [comment]
That looks fine to me. But just check how the other backends implement their flags in GN. Let's try to be as consistent w/ the other backends as possible.

**Comment by fw-brice** [comment]
Please include checks in tools/testrunner/base_runner.py in this work as well. For now, I am deleting the temporary code that was there and mostly commented out which added the `simd_riscv` flag, similar to the `simd_mips` flag.

**Comment by fw-brice** [comment]
We may also use a flag to select Sv39, Sv48, etc. The address space limit should be adjusted accordingly with these flags in _src/object/backing-store.cc_. The default is Sv39.
